name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment7-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        env:
          FORCE_UNSAFE_CONFIGURE: 1  # Set the environment variable
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: |
                    ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Print the variable
            run: echo "FORCE_UNSAFE_CONFIGURE is set to $FORCE_UNSAFE_CONFIGURE"
          - name: Apply my patch
            run: |
                 cd assignment-autotest/ 
                 git apply ../script-helpers.patch
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
